# Generated by Django 2.1.7 on 2019-02-28 03:52

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('desc', models.CharField(blank=True, max_length=1024, verbose_name='Summary')),
                ('message', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Content')),
                ('message_html', models.TextField(editable=False, verbose_name='Cotent_HTML')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Normal'), (0, 'Deleted'), (2, 'Draft')], default=1, verbose_name='Status')),
                ('is_md', models.BooleanField(default=False, verbose_name='IsMarkDown')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Time')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='Published Date')),
                ('author', models.ForeignKey(on_delete=False, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Artical',
                'verbose_name_plural': 'Artical',
                'ordering': ('-published_date',),
            },
        ),
        migrations.CreateModel(
            name='RelatedURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_des', models.CharField(max_length=256)),
                ('url_address', models.URLField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflink', to='post.Post')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=30, verbose_name='Tag')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Normal'), (0, 'Deleted')], default=1, verbose_name='Status')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
            ],
            options={
                'ordering': ['created_time'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=30, verbose_name='Topic')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Normal'), (0, 'Deleted')], default=1, verbose_name='Status')),
                ('is_nav', models.BooleanField(default=False, verbose_name='IsNav')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
            ],
            options={
                'ordering': ('created_time',),
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tag_name',
            field=models.ManyToManyField(related_name='post_tags', to='post.Tag'),
        ),
        migrations.AddField(
            model_name='post',
            name='topic_name',
            field=models.ForeignKey(on_delete=False, related_name='post_topic', to='post.Topic'),
        ),
    ]
